import {splitEqually} from '../lib/finance';
import {forgetMembership, saveMembership, strongToken, type StoredMembership} from '../lib/storage';
import type {AlbumProvider, Expense, RsvpStatus, Vibe} from '../types';
import {supabase} from './supabase';
type Snapshot={vibe:{id:string;name:string;emoji:string;type:string;description:string;starts_at:string;location:string;cover_image_url?:string;announcement?:string;currency:string;multi_currency_enabled:boolean;max_members:number;is_archived:boolean};current_member_id:string;members:Array<{id:string;name:string;color:string;is_admin:boolean;claimed:boolean}>;rsvps?:Array<{member_id:string;status:RsvpStatus}>;albums?:Array<{id:string;title:string;provider:AlbumProvider;url:string;cover_image_url?:string;photo_count:number;video_count:number;added_by_member_id?:string;added_by_name:string;created_at:string}>;expenses:Array<{id:string;description:string;amount_cents:number;paid_by:string;split_member_ids:string[];splits?:{member_id:string;share_cents:number}[];category:string;date:string;note?:string;created_by:string;deleted_at?:string;original_currency?:string;original_amount_minor?:number;exchange_rate?:number;exchange_rate_date?:string;exchange_rate_provider?:string}>;settlements:Array<{id:string;from_member_id:string;to_member_id:string;amount_cents:number;settled_at:string}>;activity:Vibe['activity']};
const client=()=>{if(!supabase)throw new Error('Vibemates is not connected yet');return supabase};
const fail=(error:unknown):never=>{console.error(error);throw new Error('Couldn’t reach Vibemates. Check your connection and try again.')};
export async function createLiveVibe(v:Vibe,creatorName=localStorage.getItem('vibemate-display-name')||'Vibemates member'){const memberToken=strongToken(),inviteToken=strongToken();const {data,error}=await client().rpc('create_vibe',{p_name:v.name,p_emoji:v.emoji,p_type:v.type,p_starts_at:v.startsAt?new Date(v.startsAt).toISOString():null,p_location:v.location,p_currency:v.currency,p_max:v.maxMembers,p_creator_name:creatorName,p_member_token:memberToken,p_invite_token:inviteToken});if(error)fail(error);const membership={vibeId:data.vibe_id,memberId:data.member_id,memberToken,inviteToken};if(v.multiCurrencyEnabled){const {error:settingsError}=await client().rpc('set_vibe_currency_options',{p_vibe:membership.vibeId,p_actor:membership.memberId,p_token:memberToken,p_enabled:true});if(settingsError)fail(settingsError);}saveMembership(membership);return membership;}
export async function loadLiveVibe(m:StoredMembership):Promise<Vibe>{const {data,error}=await client().rpc('get_vibe_snapshot',{p_vibe:m.vibeId,p_member:m.memberId,p_member_token:m.memberToken});if(error)fail(error);const s=data as Snapshot,alias=(id:string)=>id===s.current_member_id?'alex':id;return{id:s.vibe.id,name:s.vibe.name,emoji:s.vibe.emoji||'✨',type:s.vibe.type,when:s.vibe.starts_at?new Date(s.vibe.starts_at).toLocaleString('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}):'Date to be decided',startsAt:s.vibe.starts_at,location:s.vibe.location||'Location to be decided',description:s.vibe.description||'',coverImageUrl:s.vibe.cover_image_url,announcement:s.vibe.announcement,currency:s.vibe.currency,multiCurrencyEnabled:s.vibe.multi_currency_enabled,maxMembers:s.vibe.max_members,status:s.vibe.is_archived?'archived':'active',currentMemberId:'alex',inviteToken:m.inviteToken,members:s.members.map(x=>({...x,id:alias(x.id),initials:x.name.slice(0,2).toUpperCase(),isAdmin:x.is_admin})),rsvps:(s.rsvps??[]).map(x=>({memberId:alias(x.member_id),status:x.status})),albums:(s.albums??[]).map(x=>({id:x.id,title:x.title,provider:x.provider,url:x.url,coverImageUrl:x.cover_image_url,photoCount:Number(x.photo_count),videoCount:Number(x.video_count),addedByMemberId:x.added_by_member_id?alias(x.added_by_member_id):undefined,addedByName:x.added_by_name,createdAt:x.created_at})),expenses:s.expenses.map(x=>({id:x.id,description:x.description,amountCents:Number(x.amount_cents),paidBy:alias(x.paid_by),splitMemberIds:x.split_member_ids.map(alias),splits:x.splits?.map(split=>({memberId:alias(split.member_id),shareCents:Number(split.share_cents)})),category:x.category,date:x.date,note:x.note,createdBy:alias(x.created_by),deletedAt:x.deleted_at,originalCurrency:x.original_currency,originalAmountMinor:x.original_amount_minor===undefined?undefined:Number(x.original_amount_minor),exchangeRate:x.exchange_rate===undefined?undefined:Number(x.exchange_rate),exchangeRateDate:x.exchange_rate_date,exchangeRateProvider:x.exchange_rate_provider})),settlements:s.settlements.map(x=>({id:x.id,fromMemberId:alias(x.from_member_id),toMemberId:alias(x.to_member_id),amountCents:Number(x.amount_cents),settledAt:x.settled_at})),activity:s.activity};}
export async function previewInvite(token:string){const {data,error}=await client().rpc('get_vibe_by_invite',{p_raw_token:token});if(error||!data)fail(error);return data as {id:string;name:string;emoji:string;location:string;unclaimed_members:Array<{id:string;name:string}>};}
export async function joinLiveVibe(token:string,name:string,claimId?:string){const memberToken=strongToken();const request=claimId?client().rpc('claim_member',{p_raw_token:token,p_member:claimId,p_new_token:memberToken}):client().rpc('join_vibe',{p_raw_token:token,p_display_name:name,p_member_token:memberToken});const {data,error}=await request;if(error)fail(error);localStorage.setItem('vibemate-display-name',name);const membership={vibeId:data.vibe_id,memberId:data.member_id,memberToken};saveMembership(membership);return membership;}
export async function saveLiveExpense(m:StoredMembership,e:Expense){const actual=(id:string)=>id==='alex'?m.memberId:id;const splits=splitEqually(e.amountCents,e.splitMemberIds).map(x=>({member_id:actual(x.memberId),share_cents:x.shareCents}));const {error}=await client().rpc('save_expense_with_fx',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_description:e.description,p_amount:e.amountCents,p_payer:actual(e.paidBy),p_category:e.category,p_date:e.date,p_note:e.note||null,p_splits:splits,p_original_currency:e.originalCurrency||null,p_original_amount:e.originalAmountMinor||null,p_exchange_rate:e.exchangeRate||null,p_rate_date:e.exchangeRateDate||null,p_rate_provider:e.exchangeRateProvider||null});if(error)fail(error);}
export async function updateLiveExpense(m:StoredMembership,e:Expense){const actual=(id:string)=>id==='alex'?m.memberId:id;const splits=splitEqually(e.amountCents,e.splitMemberIds).map(x=>({member_id:actual(x.memberId),share_cents:x.shareCents}));const {error}=await client().rpc('update_expense_with_fx',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_expense:e.id,p_description:e.description,p_amount:e.amountCents,p_payer:actual(e.paidBy),p_category:e.category,p_date:e.date,p_note:e.note||'',p_splits:splits,p_original_currency:e.originalCurrency||null,p_original_amount:e.originalAmountMinor||null,p_exchange_rate:e.exchangeRate||null,p_rate_date:e.exchangeRateDate||null,p_rate_provider:e.exchangeRateProvider||null});if(error)fail(error);}
export async function settleLive(m:StoredMembership,from:string,to:string,amount:number){const actual=(id:string)=>id==='alex'?m.memberId:id;const {error}=await client().rpc('record_settlement',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_from:actual(from),p_to:actual(to),p_amount:amount});if(error)fail(error);}
export async function addLiveMember(m:StoredMembership,name:string,phone:string){const {error}=await client().rpc('add_member_with_phone',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_name:name,p_phone:phone});if(error)fail(error);}
export async function setLiveMemberPhone(m:StoredMembership,memberId:string,phone:string){const {error}=await client().rpc('set_member_invite_phone',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_member:memberId,p_phone:phone});if(error)fail(error);}
export async function deleteLiveExpense(m:StoredMembership,expenseId:string){const {error}=await client().rpc('delete_expense',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_expense:expenseId});if(error)fail(error);}
export async function archiveLiveVibe(m:StoredMembership){const {error}=await client().rpc('archive_vibe',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken});if(error)fail(error);}
export async function leaveLiveVibe(m:StoredMembership){const {error}=await client().rpc('leave_vibe',{p_vibe:m.vibeId,p_member:m.memberId,p_token:m.memberToken});if(error)fail(error);forgetMembership(m.vibeId);}
export async function deleteLiveVibe(m:StoredMembership){const {error}=await client().rpc('delete_vibe_permanently',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken});if(error)fail(error);forgetMembership(m.vibeId);}
export async function removeLiveMember(m:StoredMembership,memberId:string){const {error}=await client().rpc('remove_member',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_member:memberId});if(error){if(error.message.includes('member_has_financial_history')){if(confirm('This duplicate has expenses. Merge those expenses into your Admin identity and remove the duplicate?'))return mergeLiveMember(m,memberId);throw new Error('Removal cancelled.');}fail(error);}}
export async function mergeLiveMember(m:StoredMembership,memberId:string){const {error}=await client().rpc('merge_member_into_admin',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_source:memberId});if(error){if(error.message.includes('merge_has_settlements'))throw new Error('This duplicate has settlements and cannot be merged automatically.');fail(error);}}
export async function recalculateLiveSplits(m:StoredMembership){const {error}=await client().rpc('recalculate_all_expenses_equally',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken});if(error)fail(error);}
export async function setLiveRsvp(m:StoredMembership,status:RsvpStatus){const {error}=await client().rpc('set_vibe_rsvp',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_status:status});if(error)fail(error);}
export async function updateLiveOverview(m:StoredMembership,values:{startsAt:string;location:string;type:string;coverImageUrl:string;announcement:string}){const {error}=await client().rpc('update_vibe_overview',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_starts_at:values.startsAt?new Date(values.startsAt).toISOString():null,p_location:values.location,p_type:values.type,p_cover_url:values.coverImageUrl,p_announcement:values.announcement});if(error)fail(error);}
export async function addLiveAlbum(m:StoredMembership,album:{title:string;provider:AlbumProvider;url:string;coverImageUrl:string;photoCount:number;videoCount:number}){const {error}=await client().rpc('add_shared_album',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_title:album.title,p_provider:album.provider,p_url:album.url,p_cover_url:album.coverImageUrl,p_photos:album.photoCount,p_videos:album.videoCount});if(error)fail(error);}
export async function removeLiveAlbum(m:StoredMembership,albumId:string){const {error}=await client().rpc('remove_shared_album',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_album:albumId});if(error)fail(error);}
