import {splitEqually} from '../lib/finance';
import {saveMembership, strongToken, type StoredMembership} from '../lib/storage';
import type {Expense, Vibe} from '../types';
import {supabase} from './supabase';
type Snapshot={vibe:{id:string;name:string;emoji:string;type:string;description:string;starts_at:string;location:string;currency:string;max_members:number;is_archived:boolean};current_member_id:string;members:Array<{id:string;name:string;color:string;is_admin:boolean;claimed:boolean}>;expenses:Array<{id:string;description:string;amount_cents:number;paid_by:string;split_member_ids:string[];category:string;date:string;note?:string;created_by:string;deleted_at?:string}>;settlements:Array<{id:string;from_member_id:string;to_member_id:string;amount_cents:number;settled_at:string}>;activity:Vibe['activity']};
const client=()=>{if(!supabase)throw new Error('VibeMate is not connected yet');return supabase};
const fail=(error:unknown):never=>{console.error(error);throw new Error('Couldn’t reach VibeMate. Check your connection and try again.')};
export async function createLiveVibe(v:Vibe,creatorName=localStorage.getItem('vibemate-display-name')||'VibeMate member'){const memberToken=strongToken(),inviteToken=strongToken();const {data,error}=await client().rpc('create_vibe',{p_name:v.name,p_emoji:v.emoji,p_type:v.type,p_starts_at:v.startsAt?new Date(v.startsAt).toISOString():null,p_location:v.location,p_currency:v.currency,p_max:v.maxMembers,p_creator_name:creatorName,p_member_token:memberToken,p_invite_token:inviteToken});if(error)fail(error);const membership={vibeId:data.vibe_id,memberId:data.member_id,memberToken,inviteToken};saveMembership(membership);return membership;}
export async function loadLiveVibe(m:StoredMembership):Promise<Vibe>{const {data,error}=await client().rpc('get_vibe_snapshot',{p_vibe:m.vibeId,p_member:m.memberId,p_member_token:m.memberToken});if(error)fail(error);const s=data as Snapshot,alias=(id:string)=>id===s.current_member_id?'alex':id;return{id:s.vibe.id,name:s.vibe.name,emoji:s.vibe.emoji||'✨',type:s.vibe.type,when:s.vibe.starts_at?new Date(s.vibe.starts_at).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'}):'Date to be decided',startsAt:s.vibe.starts_at,location:s.vibe.location||'Location to be decided',description:s.vibe.description||'',currency:s.vibe.currency,maxMembers:s.vibe.max_members,status:s.vibe.is_archived?'archived':'active',currentMemberId:'alex',inviteToken:m.inviteToken,members:s.members.map(x=>({...x,id:alias(x.id),initials:x.name.slice(0,2).toUpperCase(),isAdmin:x.is_admin})),expenses:s.expenses.map(x=>({id:x.id,description:x.description,amountCents:Number(x.amount_cents),paidBy:alias(x.paid_by),splitMemberIds:x.split_member_ids.map(alias),category:x.category,date:x.date,note:x.note,createdBy:alias(x.created_by),deletedAt:x.deleted_at})),settlements:s.settlements.map(x=>({id:x.id,fromMemberId:alias(x.from_member_id),toMemberId:alias(x.to_member_id),amountCents:Number(x.amount_cents),settledAt:x.settled_at})),activity:s.activity};}
export async function previewInvite(token:string){const {data,error}=await client().rpc('get_vibe_by_invite',{p_raw_token:token});if(error||!data)fail(error);return data as {id:string;name:string;emoji:string;location:string;unclaimed_members:Array<{id:string;name:string}>};}
export async function joinLiveVibe(token:string,name:string,claimId?:string){const memberToken=strongToken();const request=claimId?client().rpc('claim_member',{p_raw_token:token,p_member:claimId,p_new_token:memberToken}):client().rpc('join_vibe',{p_raw_token:token,p_display_name:name,p_member_token:memberToken});const {data,error}=await request;if(error)fail(error);localStorage.setItem('vibemate-display-name',name);const membership={vibeId:data.vibe_id,memberId:data.member_id,memberToken};saveMembership(membership);return membership;}
export async function saveLiveExpense(m:StoredMembership,e:Expense){const actual=(id:string)=>id==='alex'?m.memberId:id;const splits=splitEqually(e.amountCents,e.splitMemberIds).map(x=>({member_id:actual(x.memberId),share_cents:x.shareCents}));const {error}=await client().rpc('save_expense_with_splits',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_description:e.description,p_amount:e.amountCents,p_payer:actual(e.paidBy),p_category:e.category,p_date:e.date,p_note:e.note||null,p_splits:splits});if(error)fail(error);}
export async function settleLive(m:StoredMembership,from:string,to:string,amount:number){const actual=(id:string)=>id==='alex'?m.memberId:id;const {error}=await client().rpc('record_settlement',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_from:actual(from),p_to:actual(to),p_amount:amount});if(error)fail(error);}
export async function addLiveMember(m:StoredMembership,name:string){const {error}=await client().rpc('add_manual_member',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_name:name});if(error)fail(error);}
export async function deleteLiveExpense(m:StoredMembership,expenseId:string){const {error}=await client().rpc('delete_expense',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_expense:expenseId});if(error)fail(error);}
export async function archiveLiveVibe(m:StoredMembership){const {error}=await client().rpc('archive_vibe',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken});if(error)fail(error);}
export async function removeLiveMember(m:StoredMembership,memberId:string){const {error}=await client().rpc('remove_member',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_member:memberId});if(error){if(error.message.includes('member_has_financial_history')){if(confirm('This duplicate has expenses. Merge those expenses into your Admin identity and remove the duplicate?'))return mergeLiveMember(m,memberId);throw new Error('Removal cancelled.');}fail(error);}}
export async function mergeLiveMember(m:StoredMembership,memberId:string){const {error}=await client().rpc('merge_member_into_admin',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken,p_source:memberId});if(error){if(error.message.includes('merge_has_settlements'))throw new Error('This duplicate has settlements and cannot be merged automatically.');fail(error);}}
export async function recalculateLiveSplits(m:StoredMembership){const {error}=await client().rpc('recalculate_all_expenses_equally',{p_vibe:m.vibeId,p_actor:m.memberId,p_token:m.memberToken});if(error)fail(error);}
