import {useEffect,useState} from 'react'; import {ChevronRight,Moon,RefreshCw,ShieldCheck,Sun} from 'lucide-react'; import {Logo} from './components/Logo'; import {BottomNav} from './components/Nav'; import {VibeCard} from './components/VibeCard'; import {getMemberships} from './lib/storage'; import {go,parseHash} from './lib/router'; import {loadLiveVibe} from './services/vibe-service'; import type {Vibe} from './types'; import LiveApp from './LiveApp';
import {LiveActivity,LiveMembers} from './LiveVibePages';
const KEY='vibemate-display-name';
const AppHeader=()=> <header className="topbar"><Logo/><span className="demo-badge live-badge">Live</span><button className="avatar">{(localStorage.getItem(KEY)||'VM').slice(0,2).toUpperCase()}</button></header>;
export default function LiveRoot(){const [name,setName]=useState(localStorage.getItem(KEY)||''),[draft,setDraft]=useState(''),[page,setPage]=useState(parseHash().page),[vibes,setVibes]=useState<Vibe[]>([]);const joining=parseHash().page==='join';useEffect(()=>{const h=()=>setPage(parseHash().page);addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);useEffect(()=>{if(name)Promise.all(getMemberships().map(loadLiveVibe)).then(setVibes).catch(()=>setVibes([]))},[name,page]);useEffect(()=>{if(!name)return;const update=()=>{const heading=document.querySelector('.welcome h1');if(heading?.textContent?.includes('Hey, Alex'))heading.textContent=`Hey, ${name} 👋`};update();const observer=new MutationObserver(update);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[name]);if(!name&&!joining)return <main className="welcome-page profile-onboarding"><Logo inverse/><div className="welcome-copy"><p className="eyebrow">WELCOME TO VIBEMATE</p><h1>What should your mates call you?</h1><p>This name will appear inside the vibes you create. No Google account required.</p><form onSubmit={e=>{e.preventDefault();const clean=draft.trim();if(clean.length<2)return;localStorage.setItem(KEY,clean);setName(clean)}}><label className="onboarding-label">Your name<input autoFocus required minLength={2} maxLength={60} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="e.g. Sankar"/></label><button className="primary light full">Continue <ChevronRight/></button></form></div><p className="private-note"><ShieldCheck/>Your access is remembered on this browser</p></main>;
if(page==='profile')return <><AppHeader/><main className="page subpage"><p className="eyebrow">THIS BROWSER</p><h1>Your profile</h1><section className="profile-card"><span className="big-avatar">{name.slice(0,2).toUpperCase()}</span><div><h2>{name}</h2><p>{vibes.length} private vibes</p></div></section><section className="notice"><ShieldCheck/><div><strong>Your access lives on this browser</strong><p>Clearing browser data may remove access to your vibes.</p></div></section><Theme/><button className="secondary full" onClick={()=>{const next=prompt('Change your display name',name)?.trim();if(next){localStorage.setItem(KEY,next);setName(next)}}}>Change display name</button></main><BottomNav onAdd={()=>go('/create')}/></>;
if(page==='vibes')return <><AppHeader/><main className="page subpage"><p className="eyebrow">YOUR PLANS</p><h1>All vibes</h1><section className="vibe-grid">{vibes.map(v=><VibeCard key={v.id} vibe={v}/>)}</section></main><BottomNav onAdd={()=>go('/create')}/></>;
if(page==='global-activity')return <><AppHeader/><main className="page subpage"><p className="eyebrow">ALL VIBES</p><h1>Activity</h1><div className="timeline">{vibes.flatMap(v=>v.activity.map(a=>({...a,vibe:v.name}))).map(a=><article key={a.id}><span><RefreshCw/></span><div><p><strong>{a.actor}</strong> {a.action}</p><small>{a.vibe} · {a.detail}</small><time>{a.timestamp}</time></div></article>)}</div></main><BottomNav onAdd={()=>go('/create')}/></>;
const activeVibe=vibes.find(v=>v.id===parseHash().id);if(page==='members'&&activeVibe)return <LiveMembers vibe={activeVibe} onRefresh={async()=>setVibes(await Promise.all(getMemberships().map(loadLiveVibe)))}/>;if(page==='activity'&&activeVibe)return <LiveActivity vibe={activeVibe}/>;
return <><LiveApp/><BottomNav inside={location.hash.includes('/vibe/')} onAdd={()=>location.hash.includes('/vibe/')?document.querySelector<HTMLButtonElement>('.add-expense')?.click():go('/create')}/></>}
function Theme(){const [theme,setTheme]=useState(localStorage.getItem('vibemate-theme')||'system');const choose=(x:string)=>{setTheme(x);localStorage.setItem('vibemate-theme',x);document.documentElement.dataset.theme=x};return <section className="panel"><h2>Appearance</h2><div className="theme-switch">{[['light',<Sun/>],['dark',<Moon/>],['system',<RefreshCw/>]].map(([x,icon])=><button className={theme===x?'active':''} onClick={()=>choose(String(x))} key={String(x)}>{icon}{String(x)[0].toUpperCase()+String(x).slice(1)}</button>)}</div></section>}
