-- VibeMate Pilot V1. Browser-held member tokens are bearer credentials. Only hashes
-- are stored, direct anonymous table access is denied, and mutations use RPCs.
create extension if not exists pgcrypto;
create table public.vibes(id uuid primary key default gen_random_uuid(),name text not null check(char_length(name) between 2 and 80),emoji text,vibe_type text not null,description text,starts_at timestamptz,ends_at timestamptz,location_label text,currency char(3) not null default 'AUD',max_members integer not null default 10 check(max_members between 2 and 1000),admin_member_id uuid,is_archived boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.members(id uuid primary key default gen_random_uuid(),vibe_id uuid not null references public.vibes on delete restrict,display_name text not null check(char_length(display_name) between 1 and 60),avatar_color text,member_token_hash text unique, is_admin boolean not null default false,created_by_member_id uuid,claimed_at timestamptz,created_at timestamptz not null default now());
alter table public.vibes add constraint vibes_admin_fk foreign key(admin_member_id) references public.members(id) deferrable initially deferred;
alter table public.members add constraint members_creator_fk foreign key(created_by_member_id) references public.members(id);
create table public.invites(id uuid primary key default gen_random_uuid(),vibe_id uuid not null references public.vibes on delete restrict,token_hash text unique not null,created_by_member_id uuid references public.members,expires_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default now());
create table public.expenses(id uuid primary key default gen_random_uuid(),vibe_id uuid not null references public.vibes on delete restrict,description text not null check(char_length(description) between 1 and 120),amount_cents bigint not null check(amount_cents>0),paid_by_member_id uuid not null references public.members,category text not null,expense_date date not null,note text,created_by_member_id uuid not null references public.members,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,deleted_by_member_id uuid references public.members);
create table public.expense_splits(id uuid primary key default gen_random_uuid(),expense_id uuid not null references public.expenses on delete restrict,member_id uuid not null references public.members,share_cents bigint not null check(share_cents>=0),unique(expense_id,member_id));
create table public.settlements(id uuid primary key default gen_random_uuid(),vibe_id uuid not null references public.vibes on delete restrict,from_member_id uuid not null references public.members,to_member_id uuid not null references public.members,amount_cents bigint not null check(amount_cents>0),created_by_member_id uuid not null references public.members,settled_at timestamptz not null default now(),created_at timestamptz not null default now(),check(from_member_id<>to_member_id));
create table public.activity(id uuid primary key default gen_random_uuid(),vibe_id uuid not null references public.vibes on delete restrict,actor_member_id uuid references public.members,actor_name_snapshot text not null,action_type text not null,entity_type text not null,entity_id uuid,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());
create table public.expense_versions(id uuid primary key default gen_random_uuid(),expense_id uuid not null references public.expenses,vibe_id uuid not null references public.vibes,version_number integer not null,snapshot jsonb not null,changed_by_member_id uuid not null references public.members,created_at timestamptz not null default now(),unique(expense_id,version_number));
create index members_vibe_idx on public.members(vibe_id); create index expenses_vibe_date_idx on public.expenses(vibe_id,expense_date desc) where deleted_at is null; create index splits_expense_idx on public.expense_splits(expense_id); create index activity_vibe_created_idx on public.activity(vibe_id,created_at desc); create index settlements_vibe_idx on public.settlements(vibe_id); create index invites_vibe_active_idx on public.invites(vibe_id) where revoked_at is null;
alter table public.vibes enable row level security; alter table public.members enable row level security; alter table public.invites enable row level security; alter table public.expenses enable row level security; alter table public.expense_splits enable row level security; alter table public.settlements enable row level security; alter table public.activity enable row level security; alter table public.expense_versions enable row level security;
revoke all on all tables in schema public from anon,authenticated; revoke all on all sequences in schema public from anon,authenticated;
create or replace function public.vm_hash(raw text) returns text language sql immutable security definer set search_path=public,pg_temp as $$select encode(digest(raw,'sha256'),'hex')$$; revoke all on function public.vm_hash(text) from public;
create or replace function public.vm_authorize(p_vibe uuid,p_member uuid,p_token text,p_admin boolean default false) returns public.members language plpgsql stable security definer set search_path=public,pg_temp as $$declare m public.members; begin select * into m from members where id=p_member and vibe_id=p_vibe and member_token_hash=vm_hash(p_token); if not found or (p_admin and not m.is_admin) then raise exception 'not_authorized'; end if; return m; end$$; revoke all on function public.vm_authorize(uuid,uuid,text,boolean) from public;
create or replace function public.create_vibe(p_name text,p_emoji text,p_type text,p_starts_at timestamptz,p_location text,p_currency char(3),p_max integer,p_creator_name text,p_member_token text,p_invite_token text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v vibes;m members;i invites;begin if length(p_member_token)<32 or length(p_invite_token)<24 then raise exception 'weak_token';end if;insert into vibes(name,emoji,vibe_type,starts_at,location_label,currency,max_members) values(p_name,p_emoji,p_type,p_starts_at,p_location,p_currency,p_max) returning * into v;insert into members(vibe_id,display_name,member_token_hash,is_admin,claimed_at) values(v.id,p_creator_name,vm_hash(p_member_token),true,now()) returning * into m;update vibes set admin_member_id=m.id where id=v.id;insert into invites(vibe_id,token_hash,created_by_member_id) values(v.id,vm_hash(p_invite_token),m.id) returning * into i;insert into activity(vibe_id,actor_member_id,actor_name_snapshot,action_type,entity_type,entity_id,new_data) values(v.id,m.id,m.display_name,'vibe_created','vibe',v.id,jsonb_build_object('name',v.name));return jsonb_build_object('vibe_id',v.id,'member_id',m.id,'invite_id',i.id);end$$;
create or replace function public.get_vibe_by_invite(p_raw_token text) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$select jsonb_build_object('id',v.id,'name',v.name,'emoji',v.emoji,'starts_at',v.starts_at,'location',v.location_label,'max_members',v.max_members,'unclaimed_members',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'name',m.display_name)) from members m where m.vibe_id=v.id and m.claimed_at is null),'[]'::jsonb)) from invites i join vibes v on v.id=i.vibe_id where i.token_hash=vm_hash(p_raw_token) and i.revoked_at is null and (i.expires_at is null or i.expires_at>now()) and not v.is_archived$$;
create or replace function public.claim_member(p_raw_token text,p_member uuid,p_new_token text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare m members;begin if length(p_new_token)<32 then raise exception 'weak_token';end if;update members set claimed_at=now(),member_token_hash=vm_hash(p_new_token) where id=p_member and claimed_at is null and vibe_id=(select vibe_id from invites where token_hash=vm_hash(p_raw_token) and revoked_at is null and (expires_at is null or expires_at>now())) returning * into m;if not found then raise exception 'claim_unavailable';end if;insert into activity(vibe_id,actor_member_id,actor_name_snapshot,action_type,entity_type,entity_id,new_data) values(m.vibe_id,m.id,m.display_name,'member_claimed','member',m.id,jsonb_build_object('name',m.display_name));return jsonb_build_object('vibe_id',m.vibe_id,'member_id',m.id);end$$;
create or replace function public.save_expense_with_splits(p_vibe uuid,p_actor uuid,p_token text,p_description text,p_amount bigint,p_payer uuid,p_category text,p_date date,p_note text,p_splits jsonb) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare a members;e expenses;split_total bigint;begin a:=vm_authorize(p_vibe,p_actor,p_token,false);if p_amount<=0 then raise exception 'invalid_amount';end if;if not exists(select 1 from members where id=p_payer and vibe_id=p_vibe) then raise exception 'invalid_payer';end if;select sum((x->>'share_cents')::bigint) into split_total from jsonb_array_elements(p_splits)x;if split_total<>p_amount or exists(select 1 from jsonb_array_elements(p_splits)x where not exists(select 1 from members where id=(x->>'member_id')::uuid and vibe_id=p_vibe)) then raise exception 'invalid_splits';end if;insert into expenses(vibe_id,description,amount_cents,paid_by_member_id,category,expense_date,note,created_by_member_id) values(p_vibe,p_description,p_amount,p_payer,p_category,p_date,p_note,p_actor) returning * into e;insert into expense_splits(expense_id,member_id,share_cents) select e.id,(x->>'member_id')::uuid,(x->>'share_cents')::bigint from jsonb_array_elements(p_splits)x;insert into activity(vibe_id,actor_member_id,actor_name_snapshot,action_type,entity_type,entity_id,new_data) values(p_vibe,p_actor,a.display_name,'expense_added','expense',e.id,to_jsonb(e));return e.id;end$$;
grant execute on function public.create_vibe(text,text,text,timestamptz,text,char,integer,text,text,text),public.get_vibe_by_invite(text),public.claim_member(text,uuid,text),public.save_expense_with_splits(uuid,uuid,text,text,bigint,uuid,text,date,text,jsonb) to anon;
